### ISSUE TITLE
Tracking works, but doesn't load on the display.

### ISSUE THREAD

**Issue by bizzclaw** [GitHubUsername1/Gmod_oculus_head-pos_tracking#1]
Using the CV-1 and I got the tracking to work perfectly. It's really good in fact, only problem is that I can't get the rift to actually display what's in Gmod. It just sits at a screen saying "HL2.EXE Is taking a long time to load..." Not sure if I'm missing a step, but the tutorial here is very brief.

**Comment by GitHubUsername1** [comment]
Sorry for delay. To actually view gmod on cv1 you'll need 3d driver driver software such as vorpx. However the driver software doesn't have independent headtracking (independent from the mouse). That's what  this github repository does.
